---
title: "index"
author: "Briana"
date: "11/30/2017"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
```

##Scatterplot
```{r mpg}
g <- ggplot(data=mpg, aes(x=displ, y=hwy))
g + geom_point() + theme_classic()
```


##Add color
```{r color}
ggplot(data=mpg, aes(x=displ, y=hwy, color=class)) +
  geom_point() + 
  theme_classic()
```

##Change shape for B&W figure
```{r shape}
ggplot(data=mpg, aes(x=displ, y=hwy, shape=class)) +
  geom_point() +
  theme_classic()
```

##Change point size for B&W figure
```{r size}
ggplot(data=mpg, aes(x=displ, y=hwy, size=class)) +
  geom_point() +
  theme_classic()
```

##Change point color, size and alpha
```{r alpha}
ggplot(data=mpg, aes(x=cty, y=hwy, size=class, color=fl)) +
  geom_point(alpha=0.4) +
  theme_classic()
```

##Jitter plot
```{r jitter}
ggplot(data=mpg, aes(x=cty, y=hwy, size=class, color=fl)) +
  geom_jitter(alpha=0.4) +
  theme_classic()
```

##violin plot
```{r violin}
ggplot(data=mpg, aes(x=drv, y=hwy, color=class)) +
  geom_violin() +
  theme_classic()
```

##multiple geoms
```{r mult geoms}
ggplot(data=mpg) +
  geom_point(aes(x=displ, y=hwy)) +
  geom_smooth(aes(x=displ, y=hwy)) +
  theme_classic() 
```

# Learn to wrange and tidy data
```{r gapminder, include=F}
gapminder <- readr::read_csv('https://raw.githubusercontent.com/jules32/2017-11-30-MBARI/gh-pages/data/gapminder.csv') 
```

##Manipulate data with dplyr
```{r dplyr}
#in dplyr, first argument is always the data. Subsequent arguments say what to do with it
#result is new data frame

# 1. pick out observations by value (pick out rows)
filter(gapminder, lifeExp < 29)
filter(gapminder, country %in% c("Mexico", "Peru"))
gapminder %>% 
  filter(country == "Mexico", year == 2002)

## find mean life expectancy for Sweden
### one way: 
meanLifeExp <- mean(filter(gapminder, country == "Sweden")$lifeExp)
### other way with pipe operator %>% (CONTROL SHIFT M):
gapminder %>% 
  filter(country == "Sweden") %>% 
  summarise(mean(lifeExp))

#2. select observations by variable (pick out columns)
select(gapminder, year, lifeExp)
gapminder %>% 
  select(year,lifeExp)

gapminder %>% 
  filter(country=="Cambodia") %>% 
  select(-continent, -lifeExp)

#3. create new variables in new columns with mutate
##new column for GDP
gapminder %>% 
  mutate(gdp = pop * gdpPercap)

##add index, only look at head
gapminder %>% 
  mutate(index=1:nrow(gapminder)) %>% 
  head()

##can combine mutates
gapminder %>% 
  mutate(index=1:nrow(gapminder),
         gdp=pop*gdpPercap)

# group by!
##find the maximum GDP per capita for Egypt and Vietnam
gapminder %>% 
  filter(country %in% c("Egypt","Vietnam")) %>% 
  group_by(country) %>% 
  summarise(max(gdpPercap))

##make new column for max GDP for each country
gapminder %>% 
  group_by(country) %>% 
  mutate(max(gdpPercap))

##new data frame only showing maximum GDP for each country (one entry per country)
gapminder %>% 
  group_by(country) %>% 
  mutate(max(gdpPercap)) %>% 
  filter(max(gdpPercap) == gdpPercap)

#4. order rows with arrange
## ascending order by max gdp
gapminder %>% 
  group_by(country) %>% 
  mutate(maxgdp = max(gdpPercap)) %>% 
  filter(maxgdp == gdpPercap) %>%
  arrange(maxgdp)
```
